/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;

/**
 *
 * @author yanyao
 */
public class jfInvoice extends javax.swing.JFrame {

    /**
     * Creates new form jfInvoice
     */
    public jfInvoice() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInvoice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaInvoice = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        btnExt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVOICE");

        labelInvoice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelInvoice.setText("INVOICE");

        textAreaInvoice.setColumns(20);
        textAreaInvoice.setRows(5);
        jScrollPane1.setViewportView(textAreaInvoice);

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnExt.setText("EXIT");
        btnExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnPrint)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(labelInvoice)
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExt))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrint)
                            .addComponent(btnExt))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelInvoice)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
    
        Invoice inv = new Invoice();
        String billNum = inv.toString();
        String msg ="\n";
        textAreaInvoice.append(billNum);
        if( LSystem.acc[LSystem.c].getDiscount())
        {
            textAreaInvoice.append("Discount: 80% off for this order.\n");
        }
        else
        {
            textAreaInvoice.append("Discount: -\n");
        }
       
        textAreaInvoice.append("Payment Method: Cash On Delivery\n");
       textAreaInvoice.append("------------------------------------------------------------------------------\n");
       
        double total = 0.00;
        for(int i=0;i<SF.c;i++)
        {
            msg += (i+1) + ". " + SF.fd[i].toString() + "\n";
            total += SF.fd[i].totalPrice();
        }
        
        double totalprice = total;
        if(LSystem.acc[LSystem.c].getDiscount())
        {
            totalprice *= 0.8;
        }
 
        String detail = LSystem.acc[LSystem.c].toString();
        textAreaInvoice.append(detail);
        textAreaInvoice.append("Item Detail\n-------------------------------------------------------------------------------\n");
        String invoice = inv.toString();
        textAreaInvoice.append(msg);
        textAreaInvoice.append(String.format("Total price: RM%.2f", totalprice));
        textAreaInvoice.append("\n-------------------------------------------------------------------------------\n");
        textAreaInvoice.append("\n#Payment will be done while the delivery come.\n"); 
        textAreaInvoice.append("#Please Come back again. We will happy to see you again.\n");
        textAreaInvoice.append("-------------------------------------------------------------------------------\n");
   
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtActionPerformed
        JOptionPane.showMessageDialog(null, "Thank You for your purchase in our shop.");
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_btnExtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExt;
    private javax.swing.JButton btnPrint;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInvoice;
    private javax.swing.JTextArea textAreaInvoice;
    // End of variables declaration//GEN-END:variables
}
